run:
  timeout: 5m
  deadline: 5m
  build-tags: []
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - revive
    - govet
    - gocyclo
    - gofmt
    - goimports
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - deadcode
    - varcheck
    - structcheck
    - errcheck
    - typecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - checkTypeAssertions
  goimports:
    local-prefixes: github.com/PulumiCost/pulumicost-plugin-vantage
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
