version: 2

run:
  timeout: 5m
  build-tags: []
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - revive
    - govet
    - gocyclo
    - staticcheck
    - ineffassign
    - unused
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - checkTypeAssertions

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
