version: 2

project_name: pulumicost-vantage

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: pulumicost-vantage
    main: ./cmd/pulumicost-vantage
    binary: pulumicost-vantage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**/*

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
  algorithm: sha256

release:
  github:
    owner: rshade
    name: pulumicost-plugin-vantage
  name_template: '{{ .ProjectName }} v{{ .Version }}'
  footer: |
    ### Verification

    All binaries include checksums provided in `{{ .ProjectName }}-{{ .Version }}-checksums.txt`.

    ```bash
    # Verify checksum (example for Linux amd64)
    sha256sum -c {{ .ProjectName }}-{{ .Version }}-checksums.txt --ignore-missing
    ```

    ### Installation

    Download the appropriate binary for your platform from the assets below.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
