# PulumiCost Vantage Plugin - Example Configuration
# This file demonstrates both cost_report_token and workspace_token flows.

version: 0.1
source: vantage

# Credentials: Token can be provided via environment variable (recommended)
# or inline (use environment variable for real deployments)
credentials:
  token: ${PULUMICOST_VANTAGE_TOKEN}

params:
  # ====================
  # Authentication: Choose ONE token type
  # ====================

  # Option 1: Cost Report Token (RECOMMENDED - more secure, scoped to single report)
  cost_report_token: "cr_XXXXXXXXXXXXXXXXXXXX"

  # Option 2: Workspace Token (FALLBACK - broader access)
  # workspace_token: "ws_XXXXXXXXXXXXXXXXXXXX"

  # ====================
  # Date Range
  # ====================

  # Start date (ISO 8601 format, defaults to 12 months ago)
  start_date: "2024-01-01"

  # End date (ISO 8601 format, defaults to today)
  # end_date: "2024-12-31"

  # ====================
  # Query Parameters
  # ====================

  # Granularity: "day" or "month"
  granularity: "day"

  # Dimensions to group by
  group_bys:
    - "provider"        # AWS, GCP, Azure, etc.
    - "service"         # EC2, S3, Compute Engine, etc.
    - "account"         # Account/Project ID
    - "project"         # Project name
    - "region"          # Geographic region
    - "resource_id"     # Specific resource identifier
    - "tags"            # Custom tags/labels

  # Metrics to include
  metrics:
    - "cost"                    # Net cost
    - "usage"                   # Usage quantity
    - "effective_unit_price"    # Per-unit cost
    # - "amortized_cost"        # Amortized cost (if available)
    # - "taxes"                 # Tax amounts (if available)
    # - "credits"               # Credits applied (if available)

  # ====================
  # Sync Strategy
  # ====================

  # Include forecast snapshots
  include_forecast: true

  # Lag window for incremental sync (days)
  # Typical: 3 days (D-3 to D-1) to catch late-posted charges
  # This is built into the adapter logic

  # ====================
  # Tag Filtering
  # ====================

  # Optional: Prefix filters for tags (normalized to lowercase)
  tag_prefix_filters:
    - "user:"           # Include user:* tags
    - "kubernetes.io/"  # Include Kubernetes labels
    - "app:"            # Include app:* tags

  # ====================
  # Performance & Reliability
  # ====================

  # Page size for API requests (max 5000)
  page_size: 5000

  # Request timeout in seconds
  request_timeout_seconds: 60

  # Maximum number of retries on transient failures
  max_retries: 5

# ====================
# Backfill Strategy (for CLI: --months 12)
# ====================
# When using `pulumicost-vantage backfill --months 12`:
# - Requests are chunked by month to prevent timeouts
# - Each month is fetched sequentially
# - Bookmarks track progress and allow resumption
# - For ranges >12 months, CSV export is used automatically
